import { Router } from 'express';
import { z } from 'zod';
import { readDb, writeDb } from '../store/database.js';
import { hashPassword, signToken, verifyPassword } from '../utils/auth.js';
import { requireAuth } from '../middleware/auth.js';

export const authRouter=Router();
const publicUser=(u:any)=>({id:u.id,name:u.name,email:u.email,role:u.role,verified:u.verified,preferences:u.preferences,createdAt:u.createdAt});
function setCookie(res:any, token:string, remember=false){ res.setHeader('Set-Cookie', `token=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${remember?2592000:28800}`); }
authRouter.post('/signup', async(req,res)=>{ const p=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8),remember:z.boolean().optional()}).safeParse(req.body); if(!p.success)return res.status(400).json({error:p.error.flatten()}); const db=await readDb(); if(db.users.some(u=>u.email===p.data.email.toLowerCase()))return res.status(409).json({error:'Email already registered'}); const role: 'user' | 'admin' = db.users.length ? 'user' : 'admin'; const user={id:Math.random().toString(36).slice(2)+Date.now().toString(36),name:p.data.name,email:p.data.email.toLowerCase(),passwordHash:await hashPassword(p.data.password),role,suspended:false,verified:false,createdAt:new Date().toISOString(),apiKeys:{},preferences:{theme:'light' as const,language:'en',emailNotifications:true,twoFactor:false},activity:['Account created']}; db.users.push(user); await writeDb(db); const token=signToken(user,p.data.remember); setCookie(res,token,p.data.remember); res.status(201).json({token,user:publicUser(user)}); });
authRouter.post('/login', async(req,res)=>{ const p=z.object({email:z.string().email(),password:z.string(),remember:z.boolean().optional()}).safeParse(req.body); if(!p.success)return res.status(400).json({error:p.error.flatten()}); const db=await readDb(); const user=db.users.find(u=>u.email===p.data.email.toLowerCase()); if(!user||!(await verifyPassword(p.data.password,user.passwordHash)))return res.status(401).json({error:'Invalid credentials'}); if(user.suspended)return res.status(403).json({error:'Account suspended'}); user.activity.unshift(`Login at ${new Date().toISOString()}`); await writeDb(db); const token=signToken(user,p.data.remember); setCookie(res,token,p.data.remember); res.json({token,user:publicUser(user)}); });
authRouter.post('/forgot-password', async(req,res)=>{ res.json({message:'If that email exists, a reset link will be sent by your configured email provider.'}); });
authRouter.post('/reset-password', async(req,res)=>{ const p=z.object({email:z.string().email(),newPassword:z.string().min(8)}).safeParse(req.body); if(!p.success)return res.status(400).json({error:p.error.flatten()}); const db=await readDb(); const user=db.users.find(u=>u.email===p.data.email.toLowerCase()); if(user){user.passwordHash=await hashPassword(p.data.newPassword);user.activity.unshift('Password reset completed'); await writeDb(db);} res.json({message:'Password reset complete when token verification is configured.'}); });
authRouter.post('/logout',(_req,res)=>{res.setHeader('Set-Cookie','token=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');res.json({message:'Logged out'});});
authRouter.get('/me', requireAuth, async(req,res)=>{ const db=await readDb(); const user=db.users.find(u=>u.id===req.user!.id)!; res.json({user:publicUser(user)}); });
authRouter.patch('/profile', requireAuth, async(req,res)=>{ const p=z.object({name:z.string().min(2).optional(),preferences:z.any().optional()}).safeParse(req.body); if(!p.success)return res.status(400).json({error:p.error.flatten()}); const db=await readDb(); const u=db.users.find(x=>x.id===req.user!.id)!; Object.assign(u,p.data.name?{name:p.data.name}:{}, p.data.preferences?{preferences:{...u.preferences,...p.data.preferences}}:{}); await writeDb(db); res.json({user:publicUser(u)}); });
authRouter.post('/change-password', requireAuth, async(req,res)=>{ const p=z.object({currentPassword:z.string(),newPassword:z.string().min(8)}).safeParse(req.body); if(!p.success)return res.status(400).json({error:p.error.flatten()}); const db=await readDb(); const u=db.users.find(x=>x.id===req.user!.id)!; if(!(await verifyPassword(p.data.currentPassword,u.passwordHash)))return res.status(400).json({error:'Current password is incorrect'}); u.passwordHash=await hashPassword(p.data.newPassword); u.activity.unshift('Password changed'); await writeDb(db); res.json({message:'Password changed'}); });
authRouter.delete('/account', requireAuth, async(req,res)=>{ const db=await readDb(); db.users=db.users.filter(u=>u.id!==req.user!.id); db.scans=db.scans.filter(s=>s.userId!==req.user!.id); await writeDb(db); res.setHeader('Set-Cookie','token=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'); res.json({message:'Account deleted'}); });
