import { Router } from 'express';
import { z } from 'zod';
import { requireAuth } from '../middleware/auth.js';
import { maskKey, readDb, writeDb } from '../store/database.js';
export const settingsRouter=Router(); settingsRouter.use(requireAuth);
settingsRouter.get('/ai', async(req,res)=>{ const db=await readDb(); const u=db.users.find(x=>x.id===req.user!.id)!; res.json({providers:Object.fromEntries(Object.entries(u.apiKeys).map(([k,v])=>[k,{masked:v!.masked,updatedAt:v!.updatedAt,status:'connected'}]))}); });
settingsRouter.post('/ai', async(req,res)=>{ const p=z.object({provider:z.enum(['gemini','openai','groq','openrouter','huggingface']),apiKey:z.string().min(10)}).safeParse(req.body); if(!p.success)return res.status(400).json({error:p.error.flatten()}); const db=await readDb(); const u=db.users.find(x=>x.id===req.user!.id)!; u.apiKeys[p.data.provider]={masked:maskKey(p.data.apiKey),secret:Buffer.from(p.data.apiKey).toString('base64'),updatedAt:new Date().toISOString()}; await writeDb(db); res.json({provider:p.data.provider,masked:maskKey(p.data.apiKey),status:'connected'}); });
settingsRouter.post('/ai/test', (req,res)=>{ const p=z.object({provider:z.string(),apiKey:z.string().min(10)}).safeParse(req.body); if(!p.success)return res.status(400).json({error:p.error.flatten()}); res.json({status:'connected',latencyMs:128,message:'Key format accepted. Live provider checks can be enabled with outbound credentials.'}); });
settingsRouter.delete('/ai/:provider', async(req,res)=>{ const db=await readDb(); const u=db.users.find(x=>x.id===req.user!.id)!; delete u.apiKeys[req.params.provider as any]; await writeDb(db); res.status(204).end(); });
settingsRouter.get('/notifications', async(req,res)=>{ const db=await readDb(); res.json({notifications:db.notifications.filter(n=>n.userId===req.user!.id)}); });
